---
mysql_port: 3306
mysql_root_password: changeme
databases:
  scm:
    name: 'scm'
    user: 'scm'
    pass: 'scm_password'
    type: 'mysql'
  amon:
    name: 'amon'
    user: 'amon'
    pass: 'amon_password'
    type: 'mysql'
  rman:
    name: 'rman'
    user: 'rman'
    pass: 'rman_password'
    type: 'mysql'
  nav:
    name: 'nav'
    user: 'nav'
    pass: 'nav_password'
    type: 'mysql'
  navms:
    name: 'navms'
    user: 'navms'
    pass: 'navms_password'
    type: 'mysql'
  metastore:
    name: 'metastore'
    user: 'hive'
    pass: 'hive_password'
    type: 'mysql'
  sentry:
    name: 'sentry'
    user: 'sentry'
    pass: 'sentry_password'
    type: 'mysql'
  hue:
    name: 'hue'
    user: 'hue'
    pass: 'hue_password'
    type: 'mysql'
  oozie:
    name: 'oozie'
    user: 'oozie'
    pass: 'oozie_password'
    type: 'mysql'